# @package _global_

defaults:
  - override /data: depth

name: monodepth

eval_models:
  - g2vlm

eval_datasets:
  - sintel
  - nyu-v2

invariant: median-scale  # using median(gt) / median(pred) as scale factor

overwrite: False
no_crop: True
load_img_size: 512

device: cuda

verbose: False
save_suffix: null